language: python

python:
        - 3.8.5

before_install:
        - export SECRET_KEY=preorder2021
        - export FLASK_DBMS=sqlite
        - export FILE_NAME=database.sql
        - export JWT_SECRET_KEY=test

script: 
        - python3 run.py &
